const {
    EMAIL_EXIST, ACCESS,
    USER_NOT_FOUND, WRONG_EMAIL_OR_PASSWORD, APARTMENT_NOT_EXIST,
    USER_UPDATE, USER_DELETE, CREATED, BAD_REQUEST, WRONG_TOKEN
} = require('./errors.list');

module.exports = {
    ErrorHandler: require('./ErrorHandler'),
    EMAIL_EXIST, ACCESS,
    USER_NOT_FOUND, WRONG_EMAIL_OR_PASSWORD, APARTMENT_NOT_EXIST,
    USER_UPDATE, USER_DELETE, CREATED, BAD_REQUEST, WRONG_TOKEN
};
